export const FETCH_PLACES = "FETCH_PLACES";
export const PLACE_LOADING_START = "PLACE_LOADING_START";
export const PLACE_LOADING_STOP = "PLACE_LOADING_STOP";
export const SET_PAGINATION_OBJECT = "SET_PAGINATION_OBJECT";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
export const FETCH_FILTER_OPTIONS = "FETCH_FILTER_OPTIONS";
export const FILTER_OPTIONS = "FILTER_OPTIONS";
