export const FETCH_SINGLE_PLACE_DETAIL = "FETCH_SINGLE_PLACE_DETAIL";
export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";
export const ADD_REVIEW = "ADD_REVIEW";
export const FETCH_REVIEW = "FETCH_REVIEW";
